name = "rental-system"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "rental-db"
database_id = "eef57f26-ebb5-4514-bfa2-aed14df28e0a"
