import type { RentalSystemState } from './types'

export const workbookExpenseCategories = [
  { id: 'cat-maintenance', name: 'Maintenance Charges', groupType: 'DIRECT' as const, sortOrder: 1 },
  { id: 'cat-sinking-fund', name: 'Sinking Fund Charges', groupType: 'DIRECT' as const, sortOrder: 2 },
  { id: 'cat-electricity', name: 'Electricity Charges', groupType: 'DIRECT' as const, sortOrder: 3 },
  { id: 'cat-water', name: 'Water Charges', groupType: 'DIRECT' as const, sortOrder: 4 },
  { id: 'cat-internet', name: 'Internet Charges', groupType: 'DIRECT' as const, sortOrder: 5 },
  { id: 'cat-fire-insurance', name: 'Fire Insurance Charges', groupType: 'DIRECT' as const, sortOrder: 6 },
  { id: 'cat-depreciation', name: 'Others - Depreciation', groupType: 'DIRECT' as const, isNonCash: true, sortOrder: 7 },
  { id: 'cat-assessment', name: 'Assessment monthly', groupType: 'INDIRECT' as const, sortOrder: 8 },
  { id: 'cat-quit-rent', name: 'Quit Rent monthly', groupType: 'INDIRECT' as const, sortOrder: 9 },
  { id: 'cat-bank-funding', name: 'Bank funding costs', groupType: 'INDIRECT' as const, sortOrder: 10 },
] as const

const historyMonths = [
  '2025-06', '2025-07', '2025-08', '2025-09',
  '2025-10', '2025-11', '2025-12', '2026-01',
  '2026-02', '2026-03', '2026-04', '2026-05'
]

export const workbookSampleByProperty = [
  {
    propertyId: 'prop-horizon-b0811',
    grossRentalAmount: 2000,
    expenses: {
      'cat-maintenance': 400,
      'cat-sinking-fund': 10,
      'cat-electricity': 200,
      'cat-water': 30,
      'cat-internet': 50,
      'cat-fire-insurance': 50,
      'cat-depreciation': 100,
      'cat-assessment': 50,
      'cat-quit-rent': 20,
      'cat-bank-funding': 900,
    },
  },
  {
    propertyId: 'prop-vogue-a1204',
    grossRentalAmount: 1800,
    expenses: {
      'cat-maintenance': 350,
      'cat-sinking-fund': 10,
      'cat-electricity': 150,
      'cat-water': 30,
      'cat-internet': 50,
      'cat-fire-insurance': 50,
      'cat-depreciation': 80,
      'cat-assessment': 50,
      'cat-quit-rent': 20,
      'cat-bank-funding': 850,
    },
  },
  {
    propertyId: 'prop-sentral-c3301',
    grossRentalAmount: 2200,
    expenses: {
      'cat-maintenance': 450,
      'cat-sinking-fund': 20,
      'cat-electricity': 250,
      'cat-water': 50,
      'cat-internet': 50,
      'cat-fire-insurance': 80,
      'cat-depreciation': 120,
      'cat-assessment': 50,
      'cat-quit-rent': 20,
      'cat-bank-funding': 950,
    },
  },
  {
    propertyId: 'prop-damansara-d0710',
    grossRentalAmount: 2500,
    expenses: {
      'cat-maintenance': 500,
      'cat-sinking-fund': 20,
      'cat-electricity': 280,
      'cat-water': 80,
      'cat-internet': 50,
      'cat-fire-insurance': 100,
      'cat-depreciation': 150,
      'cat-assessment': 60,
      'cat-quit-rent': 30,
      'cat-bank-funding': 1050,
    },
  },
]

export const createStarterState = (): RentalSystemState => ({
  properties: [
    {
      id: 'prop-horizon-b0811',
      serialNumber: '00001',
      unitLabel: 'B-08-11',
      address: {
        unitNumber: 'B-08-11',
        streetAddress: 'The Horizon Suites',
        cityState: 'Bangsar South, Kuala Lumpur',
      },
      kind: 'Highrise',
      ownership: 'Freehold',
      spaPrice: 720000,
      bookValue: 690000,
      marketValue: 825000,
      projectName: 'The Horizon Suites',
      developerName: 'Horizon Urban Development Sdn Bhd',
      renovations: [
        {
          id: 'reno-horizon-1',
          amountPaid: 8600,
          paymentDate: '2025-11-20',
          invoiceNumber: 'INV-HZ-1142',
          description: 'Kitchen cabinet refresh and appliance servicing',
          depreciationPeriod: 5,
          attachmentName: 'INV-HZ-1142.pdf',
        },
      ],
    },
    {
      id: 'prop-vogue-a1204',
      serialNumber: '00002',
      unitLabel: 'A-12-04',
      address: {
        unitNumber: 'A-12-04',
        streetAddress: 'Residensi Vogue',
        cityState: 'Mont Kiara, Kuala Lumpur',
      },
      kind: 'Highrise',
      ownership: 'Leasehold',
      spaPrice: 640000,
      bookValue: 612000,
      marketValue: 705000,
      projectName: 'Residensi Vogue',
      developerName: 'Vogue Habitat Sdn Bhd',
      renovations: [],
    },
    {
      id: 'prop-sentral-c3301',
      serialNumber: '00003',
      unitLabel: 'C-33-01',
      address: {
        unitNumber: 'C-33-01',
        streetAddress: 'Sentral Residences',
        cityState: 'KL Sentral, Kuala Lumpur',
      },
      kind: 'Highrise',
      ownership: 'Freehold',
      spaPrice: 950000,
      bookValue: 910000,
      marketValue: 1080000,
      projectName: 'Sentral Residences',
      developerName: 'MRCB Land',
      renovations: [
        {
          id: 'reno-sentral-1',
          amountPaid: 12800,
          paymentDate: '2025-12-12',
          invoiceNumber: 'INV-SR-2208',
          description: 'Wardrobe replacement and lighting works',
          depreciationPeriod: 10,
          attachmentName: 'INV-SR-2208.pdf',
        },
      ],
    },
    {
      id: 'prop-damansara-d0710',
      serialNumber: '00004',
      unitLabel: 'D-07-10',
      address: {
        unitNumber: 'D-07-10',
        streetAddress: 'Damansara Grove',
        cityState: 'Petaling Jaya, Selangor',
      },
      kind: 'Highrise',
      ownership: 'Freehold',
      spaPrice: 580000,
      bookValue: 552000,
      marketValue: 640000,
      projectName: 'Damansara Grove',
      developerName: 'Grove Living Sdn Bhd',
      renovations: [],
    },
  ],
  tenants: [
    {
      id: 'tenant-michael',
      name: 'Michael Chang',
      nricPassport: 'A89332145',
      email: 'm.chang@techcorp.com',
      mobile: '+60 12-345 6789',
    },
    {
      id: 'tenant-sarah',
      name: 'Sarah Jenkins',
      nricPassport: 'P8744129',
      email: 's.jenkins@example.com',
      mobile: '+60 17-288 4410',
    },
    {
      id: 'tenant-elena',
      name: 'Elena Rodriguez',
      nricPassport: 'XK552104',
      email: 'elena.r@designstudio.my',
      mobile: '+60 11-2208 7710',
    },
    {
      id: 'tenant-aisha',
      name: 'Aisha Rahman',
      nricPassport: '900214-10-5532',
      email: 'aisha.rahman@novamed.my',
      mobile: '+60 13-771 5520',
    },
    {
      id: 'tenant-daniel',
      name: 'Daniel Tan',
      nricPassport: '881009-14-2381',
      email: 'daniel.tan@finlite.my',
      mobile: '+60 16-904 1188',
    },
  ],
  tenancies: [
    {
      id: 'tenancy-horizon-michael',
      propertyId: 'prop-horizon-b0811',
      tenantId: 'tenant-michael',
      commencementDate: '2025-12-01',
      keyCollectionDate: '2025-12-02',
      moveInDate: '2025-12-05',
      expirationDate: '2026-12-01',
      tenure: '12 months',
      airSelangorAccount: '88129304',
      tnbAccount: '22394019',
      tmAccount: 'Unifi-8811',
      status: 'Active',
      closedEarly: false,
      rentalTerms: {
        rentalDeposit: 7000,
        surcharge: 0,
        monthlyGross: 3500,
        dateOfCollection: '2026-05-01',
        serviceFeeDeduction: 50,
        monthlyNet: 3446,
        dateOfNetRemitted: '2026-05-03',
        cumulativeGross: 21000,
        cumulativeNet: 20676,
        lateCollectionFlag: false,
      },
      deductions: {
        maintenanceCharges: 420,
        quitRent: 30,
        assessment: 95,
        utilityCharges: 0,
        fireInsurancePremium: 42,
        sinkingFundPayment: 120,
        miscellaneousCharges: 0,
        bankCostOfFunds: 1180,
        depreciationCost: 143,
      },
    },
    {
      id: 'tenancy-vogue-sarah',
      propertyId: 'prop-vogue-a1204',
      tenantId: 'tenant-sarah',
      commencementDate: '2025-09-15',
      keyCollectionDate: '2025-09-16',
      moveInDate: '2025-09-20',
      expirationDate: '2026-09-14',
      tenure: '12 months',
      airSelangorAccount: '77412880',
      tnbAccount: '11394820',
      tmAccount: 'Unifi-1204',
      status: 'Late Collection',
      closedEarly: false,
      rentalTerms: {
        rentalDeposit: 6400,
        surcharge: 120,
        monthlyGross: 3200,
        dateOfCollection: '2026-05-14',
        serviceFeeDeduction: 64,
        monthlyNet: 3256,
        dateOfNetRemitted: '',
        cumulativeGross: 25600,
        cumulativeNet: 25008,
        lateCollectionFlag: true,
      },
      deductions: {
        maintenanceCharges: 390,
        quitRent: 25,
        assessment: 88,
        utilityCharges: 160,
        fireInsurancePremium: 40,
        sinkingFundPayment: 110,
        miscellaneousCharges: 80,
        bankCostOfFunds: 1020,
        depreciationCost: 0,
      },
    },
    {
      id: 'tenancy-sentral-elena',
      propertyId: 'prop-sentral-c3301',
      tenantId: 'tenant-elena',
      commencementDate: '2025-03-01',
      keyCollectionDate: '2025-03-02',
      moveInDate: '2025-03-05',
      expirationDate: '2026-06-18',
      tenure: '15 months',
      airSelangorAccount: '55194002',
      tnbAccount: '55420091',
      tmAccount: 'Unifi-3301',
      status: 'Expiring',
      closedEarly: false,
      rentalTerms: {
        rentalDeposit: 9600,
        surcharge: 0,
        monthlyGross: 4800,
        dateOfCollection: '2026-05-02',
        serviceFeeDeduction: 96,
        monthlyNet: 4704,
        dateOfNetRemitted: '2026-05-04',
        cumulativeGross: 67200,
        cumulativeNet: 65856,
        lateCollectionFlag: false,
      },
      deductions: {
        maintenanceCharges: 620,
        quitRent: 48,
        assessment: 130,
        utilityCharges: 0,
        fireInsurancePremium: 62,
        sinkingFundPayment: 180,
        miscellaneousCharges: 0,
        bankCostOfFunds: 1540,
        depreciationCost: 107,
      },
    },
    {
      id: 'tenancy-damansara-aisha',
      propertyId: 'prop-damansara-d0710',
      tenantId: 'tenant-aisha',
      commencementDate: '2025-07-01',
      keyCollectionDate: '2025-07-03',
      moveInDate: '2025-07-06',
      expirationDate: '2026-07-01',
      tenure: '12 months',
      airSelangorAccount: '92310577',
      tnbAccount: '88310020',
      tmAccount: 'Unifi-0710',
      status: 'Closed Early',
      closedEarly: true,
      rentalTerms: {
        rentalDeposit: 5600,
        surcharge: 0,
        monthlyGross: 2800,
        dateOfCollection: '2026-04-01',
        serviceFeeDeduction: 56,
        monthlyNet: 2744,
        dateOfNetRemitted: '2026-04-02',
        cumulativeGross: 28000,
        cumulativeNet: 27440,
        lateCollectionFlag: false,
      },
      deductions: {
        maintenanceCharges: 330,
        quitRent: 22,
        assessment: 72,
        utilityCharges: 0,
        fireInsurancePremium: 36,
        sinkingFundPayment: 90,
        miscellaneousCharges: 0,
        bankCostOfFunds: 890,
        depreciationCost: 0,
      },
    },
    {
      id: 'tenancy-horizon-daniel',
      propertyId: 'prop-horizon-b0811',
      tenantId: 'tenant-daniel',
      commencementDate: '2026-01-10',
      keyCollectionDate: '2026-01-10',
      moveInDate: '2026-01-12',
      expirationDate: '2027-01-09',
      tenure: '12 months',
      airSelangorAccount: '88129304',
      tnbAccount: '22394019',
      tmAccount: 'Unifi-8811',
      status: 'Active',
      closedEarly: false,
      rentalTerms: {
        rentalDeposit: 7200,
        surcharge: 0,
        monthlyGross: 3600,
        dateOfCollection: '2026-05-01',
        serviceFeeDeduction: 72,
        monthlyNet: 3528,
        dateOfNetRemitted: '2026-05-02',
        cumulativeGross: 18000,
        cumulativeNet: 17640,
        lateCollectionFlag: false,
      },
      deductions: {
        maintenanceCharges: 420,
        quitRent: 30,
        assessment: 95,
        utilityCharges: 0,
        fireInsurancePremium: 42,
        sinkingFundPayment: 120,
        miscellaneousCharges: 0,
        bankCostOfFunds: 1180,
        depreciationCost: 143,
      },
    },
  ],
  rentCollections: historyMonths.flatMap(month => [
    {
      id: `rc-michael-${month}`,
      tenancyId: 'tenancy-horizon-michael',
      expectedCollectionDate: `${month}-01`,
      actualCollectionDate: `${month}-01`,
      amountCollected: 3500,
      serviceAdminFee: 50,
      sst: 4,
      dateRemitted: `${month}-03`,
    },
    {
      id: `rc-sarah-${month}`,
      tenancyId: 'tenancy-vogue-sarah',
      expectedCollectionDate: `${month}-01`,
      actualCollectionDate: month === '2026-05' ? `${month}-14` : `${month}-05`,
      amountCollected: month === '2026-05' ? 2200 : 2500,
      serviceAdminFee: 64,
      sst: 5.12,
      dateRemitted: month === '2026-05' ? '' : `${month}-06`,
      notes: month === '2026-05' ? 'Partial and late' : undefined,
    },
    {
      id: `rc-elena-${month}`,
      tenancyId: 'tenancy-sentral-elena',
      expectedCollectionDate: `${month}-01`,
      actualCollectionDate: `${month}-02`,
      amountCollected: 4800,
      serviceAdminFee: 96,
      sst: 7.68,
      dateRemitted: `${month}-04`,
    },
    {
      id: `rc-aisha-${month}`,
      tenancyId: 'tenancy-damansara-aisha',
      expectedCollectionDate: `${month}-01`,
      actualCollectionDate: `${month}-01`,
      amountCollected: 2800,
      serviceAdminFee: 56,
      sst: 4.48,
      dateRemitted: `${month}-02`,
    },
    {
      id: `rc-daniel-${month}`,
      tenancyId: 'tenancy-horizon-daniel',
      expectedCollectionDate: `${month}-01`,
      actualCollectionDate: `${month}-01`,
      amountCollected: 3600,
      serviceAdminFee: 72,
      sst: 5.76,
      dateRemitted: `${month}-02`,
    },
  ]),
  depositTransactions: [
    {
      id: 'dep-michael-r',
      tenancyId: 'tenancy-horizon-michael',
      date: '2025-12-01',
      type: 'Received',
      amount: 7000,
    },
    {
      id: 'dep-aisha-r',
      tenancyId: 'tenancy-damansara-aisha',
      date: '2025-07-01',
      type: 'Received',
      amount: 5600,
    },
    {
      id: 'dep-aisha-refund',
      tenancyId: 'tenancy-damansara-aisha',
      date: '2026-04-15',
      type: 'Refunded',
      amount: 3000,
      notes: 'Partial refund after early closure',
    },
  ],
  expenseTransactions: historyMonths.flatMap(month => [
    {
      id: `exp-horizon-${month}-maint`,
      tenancyId: 'tenancy-horizon-michael',
      propertyId: 'prop-horizon-b0811',
      datePaid: `${month}-08`,
      expenseType: 'Maintenance',
      amount: 420,
      invoiceNumber: `MNT-HZ-${month.replace('-','')}`,
    },
    {
      id: `exp-vogue-${month}-utility`,
      tenancyId: 'tenancy-vogue-sarah',
      propertyId: 'prop-vogue-a1204',
      datePaid: `${month}-20`,
      expenseType: 'Utility',
      amount: 160 + Math.floor(Math.random() * 40 - 20),
      invoiceNumber: `UTIL-VG-${month.replace('-','')}`,
    },
    {
      id: `exp-sentral-${month}-fund`,
      tenancyId: 'tenancy-sentral-elena',
      propertyId: 'prop-sentral-c3301',
      datePaid: `${month}-05`,
      expenseType: 'Sinking Fund',
      amount: 180,
      invoiceNumber: `SF-SR-${month.replace('-','')}`,
    },
  ]),
  expenseCategories: workbookExpenseCategories.map((category) => ({ ...category })),
  monthlyRentalIncomes: historyMonths.flatMap(month => 
    workbookSampleByProperty.map((item) => ({
      id: `income-${item.propertyId}-${month}`,
      propertyId: item.propertyId,
      periodMonth: month,
      grossRentalAmount: item.grossRentalAmount,
    }))
  ),
  monthlyExpenseEntries: historyMonths.flatMap(month => 
    workbookSampleByProperty.flatMap((item) =>
      Object.entries(item.expenses).map(([expenseCategoryId, amount]) => ({
        id: `expense-${item.propertyId}-${expenseCategoryId}-${month}`,
        propertyId: item.propertyId,
        periodMonth: month,
        expenseCategoryId,
        amount,
      }))
    )
  ),
  tenantActivities: [
    {
      id: 'activity-michael-collection',
      tenancyId: 'tenancy-horizon-michael',
      date: '2026-05-01',
      type: 'Collection',
      notes: 'Collected full rental on due date and remitted on 03 May.',
    },
    {
      id: 'activity-sarah-reminder',
      tenancyId: 'tenancy-vogue-sarah',
      date: '2026-05-15',
      type: 'Reminder',
      notes: 'Called tenant after partial payment, balance still outstanding.',
    },
    {
      id: 'activity-elena-renewal',
      tenancyId: 'tenancy-sentral-elena',
      date: '2026-06-01',
      type: 'Renewal',
      notes: 'Renewal review started, lease expires this month.',
    },
    {
      id: 'activity-aisha-termination',
      tenancyId: 'tenancy-damansara-aisha',
      date: '2026-04-15',
      type: 'Termination',
      notes: 'Closed early and processed partial deposit refund.',
    },
  ],
})
